"""The regime plate: what each instrument reports in each band of the ladder.

Three schematics used to live here, drawn in matplotlib. Two of them -- the
protocol and the crossed axes -- are now drawn in the manuscript itself in
TikZ, where they inherit its font and its point sizes instead of approximating
them in DejaVu Sans at a scale factor. They are not reproduced here, and their
old PDFs are deleted rather than left on disk, because a stale plate that can
still be \includegraphics'd is worse than no plate.

This one stayed behind because it is the awkward case: a schematic that carries
measured numbers. Typed into the .tex it would be the one figure in the paper
whose numbers are not read from the stored measurements; drawn in matplotlib it
would be the one figure whose type does not match the page. So it is generated
here and emitted as a TikZ fragment the manuscript \input{}s -- numbers from
the stats files, typesetting from the document.

Usage:
  python scripts/build_schematic_figures.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def fig_regimes(out: Path, stats: dict[str, Any],
                probe_stats: dict[str, Any]) -> None:
    """Three regimes, and what each instrument reports in each.

    Emitted as a TikZ fragment rather than a raster. This plate is a schematic
    that carries measured numbers: drawn in matplotlib it printed DejaVu Sans
    beside the manuscript's Latin Modern and guessed every point size against a
    scale factor, and drawn by hand in the .tex it would have had typed numbers,
    which is the one thing this project does not do. A generated fragment is
    both -- the numbers below are read from the stats files, and the type is the
    document's own.

    Written to docs/paper/tables/ rather than figures/, because it is
    \\input{} and not \\includegraphics.
    """
    gate = stats["gate_by_grader"]["Qwen2.5-3B"]
    row45 = next(r for r in gate if r["bits"] == 4.5)
    row25 = next(r for r in gate if r["bits"] == 2.5)
    # The corrected scorer's probe refit, not review_stats.json's. This plate is
    # the paper on one page and it must not be the one place where the original
    # grading survives unlabelled.
    probe = next(r for r in probe_stats["scorers"]["letter"]["Qwen2.5-3B"]["rows"]
                 if r["bits"] == 4.5)

    def pct(value: float, decimals: int = 1) -> str:
        return f"{100 * value:.{decimals}f}\\%"

    bands = [
        ("INERT", "FP16 -- 8.5 bits", "cgink!45", "cggrey", [
            (r"refusal shift\,$\dagger$", "$+0.4$ pp", ""),
            ("phrase list vs judge", "agree", ""),
            ("degenerate", "0.0\\%", ""),
            ("probe $d'$ retained", "$\\sim$100\\%", ""),
        ]),
        ("DRIFT", "8.5 -- 4.5 bits", "cgwarn", "cgwarn!7", [
            (r"refusal shift\,$\dagger$", "1.15 pp / bit", "cgwarn"),
            ("phrase list vs judge",
             f"{pct(row45['marker_composite'])} vs {pct(row45['judge_composite'])}",
             "cgred"),
            ("degenerate", pct(row45["degenerate_composite"]), ""),
            ("probe $d'$ retained", pct(probe["retained_mean"], 0), "cgsafe"),
        ]),
        ("COLLAPSE", "3.5 bits and below", "cgred", "cgred!6", [
            ("refusal rate", "meaningless", ""),
            ("same list, gate swapped",
             f"{pct(row25['marker_nll'])} vs {pct(row25['marker_composite'])}",
             "cgred"),
            ("degenerate", pct(row25["degenerate_composite"]), "cgred"),
            ("probe $d'$ retained", "n/a", ""),
        ]),
    ]

    lines = [
        r"% Generated by scripts/build_schematic_figures.py -- do not edit.",
        r"% Every number here is read from review_stats.json and",
        r"% probe_corrected.json at build time rather than typed.",
        r"\begin{tikzpicture}[font=\footnotesize,",
        r"  band/.style={draw, rounded corners=2pt, minimum width=4.95cm,",
        r"               minimum height=3.55cm, anchor=north west},",
        r"  head/.style={font=\bfseries},",
        r"  key/.style={font=\scriptsize, cgink!65},",
        r"  val/.style={font=\scriptsize\bfseries}]",
    ]
    for index, (name, span, edge, fill, rows) in enumerate(bands):
        x = index * 5.25
        lines += [
            rf"  \node[band, draw={edge}, fill={fill}] (b{index}) at ({x}, 0) {{}};",
            rf"  \node[head, {edge}] at ({x + 2.475}, -0.38) {{{name}}};",
            rf"  \node[key] at ({x + 2.475}, -0.72) {{{span}}};",
        ]
        for k, (label, value, colour) in enumerate(rows):
            y = -1.16 - k * 0.60
            tint = colour or "cgink"
            lines += [
                rf"  \node[key] at ({x + 2.475}, {y:.2f}) {{{label}}};",
                rf"  \node[val, {tint}] at ({x + 2.475}, {y - 0.26:.2f}) {{{value}}};",
            ]
    lines += [
        r"  \draw[cgarrow] (0, -3.92) -- (15.45, -3.92);",
        r"  \node[key, anchor=west] at (0, -4.16) {16 bits};",
        r"  \node[key] at (7.72, -4.16) {stored bits per parameter, decreasing};",
        r"  \node[key, anchor=east] at (15.45, -4.16) {2.5 bits};",
        r"\end{tikzpicture}",
    ]

    target = out.parent / "tables" / "fig_regimes.tex"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  {target.name} (TikZ fragment)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", type=Path, default=Path("docs/paper/figures"))
    args = ap.parse_args()

    repo = Path(__file__).resolve().parents[1]
    print(f"writing to {args.out}")

    stats_path = repo / "docs/paper/review_stats.json"
    probe_path = repo / "docs/paper/probe_corrected.json"
    if stats_path.exists() and probe_path.exists():
        fig_regimes(args.out,
                    json.loads(stats_path.read_text(encoding="utf-8")),
                    json.loads(probe_path.read_text(encoding="utf-8")))
    else:
        print("  fig_regimes SKIPPED: review_stats.json or "
              "probe_corrected.json absent, and this plate carries measured "
              "numbers rather than placeholders")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
